host:
routes:
  - /signup
  - /login
  - /v1/userinfo/:uuid
  - /v1/roomlist
  - /login/mobile
  - /signup/mobile
  - /signup/mobile/exist
  - /v1/rooms/:uuid/whiteboard
  - /v1/logout
openJwt: true
logConfig:
  path: ./run/niuNiuWhiteBoard
  level: debug
dbConfig:
  driverName: mysql
  dsn: root:password@tcp(127.0.0.1:3306)/niuNiuWhiteBoard?charset=utf8mb4&parseTime=true&loc=Local
  showSql: true
  showExecTime: false
  maxIdle: 10
  maxOpen: 200
qiniuService:
  accessKey: UKxFwgBIB-2XNAb3gRZiicO09ZrlZqGTn3wfho_x
  secretKey: IwHAY5Wkkd42i8JTBQ7BFjx9CpTyAXst5x0ImTqF
  rtcAppId: gqo29t6e5
whiteboard:
  ak: hpTBCFkXHjyZjktpyaFa6PIE2LCqItrUG8bwJiuXjssi35WdSujxJiiHjw8XOKnt



