dbConfig:
  driverName: mysql
  dsn: root:password.@tcp(127.0.0.1:3306)/niuNiuSDK?charset=utf8mb4&parseTime=true&loc=Local
  showSql: true
  showExecTime: false
  maxIdle: 10
  maxOpen: 200
log:
  path: ./run/niuNiuWhiteBoard
  level: debug
redisConfig:
  addr: localhost:6379
  password:
  dB: 0
  poolSize: 20



